### PR TITLE
dGPU SR-IOV patches

### PR DESCRIPTION
**Pull request by phreer**
This will close https://github.com/projectceladon/linux-intel-lts2022/pull/18.

### CODE REVIEW

**Review by feijiang1 — APPROVED** [review]
LGTM

**Review by xyzhao2018 — COMMENTED** [review]
Please add "Test Done" part before merge.

**Comment by phreer** [comment]
> Please add "Test Done" part before merge.

Done. Please review and approve it!

**Review by feijiang1 — APPROVED** [review]
LGTM

**Pull request merged**
