### PR TITLE
QNX: Add QNX ivhsmem support for optee

### PR DESCRIPTION
**Pull request by ceiba1985**
OPTEE synced with the REE world through vdev shm
mechanism.

Tracked-On: OAM-124009

### CODE REVIEW

**Review by jingdlu — APPROVED** [review]
LGTM

**Review by xyzhao2018 — COMMENTED** [review]
Can we use the #ifdef to diff acrn and qnx?

**Review by xyzhao2018 — APPROVED** [review]

**Review by xyzhao2018 — COMMENTED** [review]
Please add test done part.

**Comment by xyzhao2018** [comment]
> Can we use the #ifdef to diff acrn and qnx?

after sync with owner, the target is one image can run on both acrn and qnx, so don't need to add #ifdef.

**Review by xyzhao2018 — COMMENTED** [review]
where defined these two PCI ids?

**Pull request merged**
