### PR TITLE
drm/virtio: set max vblank number

### PR DESCRIPTION
**Pull request by bosheng1**
vblank array in virtio gpu struct is zero array, and driver does not allocate buffer for it, so set max vblank number and check it.

Tracked-On: OAM-126006

### CODE REVIEW

**Comment by bosheng1** [comment]
@liuhang-bit please review it.

**Review by feijiang1 — APPROVED** [review]
LGTM

**Review by xyzhao2018 — COMMENTED** [review]
Please add test done part.

**Comment by bosheng1** [comment]
> Please add test done part.

done. thanks for your comment.

**Review by feijiang1 — APPROVED** [review]
LGTM

**Pull request merged**
