### PR TITLE
Mofify for ivshmem

### PR DESCRIPTION
**Pull request by weichenli-intel**
This patch add a function to map the gpa to ivshmem offset.

Test done:
1. QNX + virtio camera + IPU Camera
2. QNX + virtio camera + UVC Camera

Tracked-On: OAM-124423

### CODE REVIEW

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by xyzhao2018 — APPROVED** [review]

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
Please add Tests done to commit message.
"This patch add a function to implement the map dma address to ivshmem
offset feature." => Correct me if i'm wrong is this change is about mapping ivshmem page to dma address?

**Comment by weichenli-intel** [comment]
> Please add Tests done to commit message. "This patch add a function to implement the map dma address to ivshmem offset feature." => Correct me if i'm wrong is this change is about mapping ivshmem page to dma address?

Yes.

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by xyzhao2018 — APPROVED** [review]

**Review by JeevakaPrabu — APPROVED** [review]

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by xyzhao2018 — APPROVED** [review]

**Pull request merged**
